export const expeditions = [
    {
        id: 1,
        title: 'Cañón del Río Mezquital',
        location: 'Durango, México',
        coords: [23.9, -104.65],
        duration: '3 días',
        difficulty: 'Intermedio',
        difficultyColor: 'text-yellow-400',
        date: '15 Jun 2026',
        price: '$4,500 MXN',
        description: 'Explora uno de los cañones más impresionantes del norte de México.',
        type: 'Cañón · Senderismo',
    },
    {
        id: 2,
        title: 'Cumbre del Volcán Nevado',
        location: 'Colima, México',
        coords: [19.57, -103.62],
        duration: '2 días',
        difficulty: 'Avanzado',
        difficultyColor: 'text-red-400',
        date: '28 Jul 2026',
        price: '$5,200 MXN',
        description: 'Asciende a la cumbre con vistas que cambiarán tu perspectiva.',
        type: 'Volcán · Alta Montaña',
    },
    {
        id: 3,
        title: 'Rafting Río Actopan',
        location: 'Veracruz, México',
        coords: [19.5, -96.6],
        duration: '1 día',
        difficulty: 'Principiante',
        difficultyColor: 'text-emerald-400',
        date: '10 Ago 2026',
        price: '$2,800 MXN',
        description: 'Navega los rápidos más emocionantes rodeado de selva tropical.',
        type: 'Río · Rafting',
    },
];